.TH bzrlog 1 "27 Sep 2010" bikeshed "bikeshed"
.SH NAME
bzrlog - show the bzr log, including merges, but pipe to a pager

.SH SYNOPSIS
\fBbzrlog\fP [ARGS]

.SH DESCRIPTION
\fBbzrlog\fP is a program that shows a bzr log, including merges, but pipes it to a pager (sort of like git).

Note that ARGS is simply passed through to 'bzr log'.

.SH SEE ALSO
\fBbzr\fP(1)\fP

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
