#!/bin/sh
#
#    bzrp - run bzr commands, but sensibly page the output
#
#    Copyright (C) 2008-2010 Dustin Kirkland <kirkland@ubuntu.com>
#
#    Authors:
#        Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

cmd=$(shift)

pager=$(readlink /etc/alternatives/pager)
if [ $pager = /bin/less ]; then
	opts="-F -R -X"
fi
# NOTE: The $opts are specific to vi-compatible pagers, like 'less'.
#       It would be nice to have a better way of detecting this.
#       Currently, these support:
#       -F to exit if output fits on one screen
#       -R for color (see 'cdiff')
#       -X to disable screen clearing

exec /usr/bin/bzr $cmd "$@" | sensible-pager $opts
