.TH cloud-sandbox 1 "10 Oct 2011" bikeshed "bikeshed"
.SH NAME
cloud-sandbox \- launch a cloud instance and ssh directly into it, as a 'sandbox' system

.SH SYNOPSIS
\fBcloud-sandbox\fP [instance-type [ubuntu-release]] [ec2-run-instance-options]

.SH DESCRIPTION
\fBcloud-sandbox\fP is a program that launches a cloud instance (EC2 by default), automatically generates ssh host keys, ssh's into the launched system, and prompts the user for instance termination on exit.

\fBcloud-sandbox\fP does the following:
 - conveniently supports simple parameters for instance-type and ubuntu-release, by passing those to \fBubuntu-ec2-run\fP(1)\fP
 - generates ssh-host keys locally using \fBssh-keygen\fP(1)\fP, and passes them to the instance
 - automatically adds host key fingerprints to a local host keys file, \fI$HOME/.ssh/known_hosts.cloud\fP, which removes the interactive fingerprint prompt
 - uses \fBssh-import-id\fP(1)\fP in the instance to import the user's public SSH key, if the environment variable $LAUNCHPAD_ID exists
 - uses \fBbootmail\fP(1) to send the user email noting that the instance has booted, if the environment variable $BOOTMAIL exists and is a valid email address
 - waits in a loop for \fBsshd\fP(8) to start on the cloud instance
 - execs an \fBssh\fP(1) session to the instance
 - upon exit, interactively prompts the user if they want to immediately terminate the instance and remote the ssh known host key

.SH EXAMPLE
 cloud-sandbox

 cloud-sandbox m1.large

 cloud-sandbox t1.micro lucid

.SH SEE ALSO
\fBubuntu-ec2-run\fP(1)\fP, \fBssh-import-id\fP(1)\fP, \fBbootmail\fP(1)\fP, \fBssh-keygen\fP(1)\fP

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
