.TH dchb 1 "6 Oct 2010" bikeshed "bikeshed"
.SH NAME
dchb - open the debian/changelog in sensible editor, appending a line showing the current files that have been modified

.SH SYNOPSIS
\fBdchb\fP

.SH DESCRIPTION
\fBdchb\fP is a program that determines the files that have been modified in the current bzr tree, and opens \fIdebian/changelog\fP for editing, using \fBdch\fP(1), and appending a changelog entry for the current list of modified files.

.SH SEE ALSO
\fBbzr\fP(1)\fP, \fBsensible-editor\fP(1), \fBdch\fP(1)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
