.TH dman 1 "27 Sep 2010" bikeshed "bikeshed"
.SH NAME
dman \- download and read manpages from the internet, rather than the local system

.SH SYNOPSIS
\fBdman\fP [TOPIC]

.SH DESCRIPTION
\fBdman\fP is a script that remotely retrieves manpages from http://manpages.ubuntu.com, but reads them on the local system.

This is often useful to read a manpage of a utility that you do not have installed on the local system.

It will cycle through each manpage section available for a given TOPIC.

.SH EXAMPLE
 dman open

.SH CAVEATS
Note that the network operations will be a little slower than perhaps you are used to, when reading a manpage.  Also note that you must be internet-connected, and able to access manpages.ubuntu.com for this utility to be useful.  Finally, the algorithm that \fBdman\fP uses to retrieve remote pages is considerably simpler than that of \fBman\fP(1).

.SH SEE ALSO
\fBman\fP(1)\fP

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
