.TH multi-push 1 "6 Feb 2013" bikeshed "bikeshed"
.SH NAME
\fBmulti-push\fP \- push a source tree to multiple source repositories

.SH SYNOPSIS
\fBmulti-push\fP $@

\fBmulti-push-init\fP

.SH DESCRIPTION
\fBmulti-push\fP is a script that will first push a \fBbzr\fP(1) source tree up to \fILaunchpad.net\fI, then export that tree to \fBgit\fP(1), and push that tree up to \fIGithub.com\fP.

It is often useful to have a backup copy of your source tree, and it enables wider sharing of your source code across other development communities.

.SH EXAMPLE
 dman open

.SH CAVEATS
Currently, the \fBbzr\fP(1)\fP on \fILaunchpad.net\fI is assumed to be the master and the \fBgit\fP(1) tree on \fIGithub.com\fP is assumed to be the slave.

.SH SEE ALSO
\fBbzr\fP(1)\fP, \fBgit\fP(1)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
