.TH name-search 1 "1 Oct 2014" bikeshed "bikeshed"
.SH NAME
\fBname-search\fP \- check if a certain name is available for use on a handful of open source related sites

.SH SYNOPSIS
\fBname-search\fP $@

.SH DESCRIPTION
\fBname-search\fP is a script that will check if a given namespace is available in the Ubuntu apt archive, on Github.com, on Launchpad.net, and if domain names might be available.

This may be helpful when selecting the name of an open source project, for instance.

.SH SEE ALSO
\fBwget\fP(1), \fBnslookup\fP(1), \fBapt-cache\fP(8)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
