#!/bin/sh
#
#    pbput, pbputs, pbget - put and get binary files to/from pastebin.com
#    Copyright (C) 2010 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#    Authors: Dustin Kirkland <dustin.kirkland@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROG=$(basename $0)
URL="http://pastebin.com"

# Create a secure tempfile
u=$(umask)
umask 177
TEMP=$(mktemp)
umask "$u"
trap "rm -f $TEMP 2>/dev/null || true" EXIT HUP INT QUIT TERM

case "$PROG" in
	pbget)
		url=$(echo "$1" | sed -e "s:.com/:.com/download.php?i=:")
		wget -q -O- "$url" | base64 -d | lzma -d > "$TEMP"
		# Support secure uploads
		gpg -d "$TEMP" 2>/dev/null || cat "$TEMP"
	;;
	pbput|pbputs)
		if [ -r "$1" ]; then
			# Read file from argument
			cat "$1" > "$TEMP"
		else
			# Read from standard in
			cat /dev/stdin "$TEMP"
		fi
		if [ "$PROG" = "pbputs" ]; then
			mv -f "$TEMP" "$TEMP".in
			cat "$TEMP".in | gpg -c > "$TEMP"
			rm -f "$TEMP".in
		fi
		lzma -9 -f -c "$TEMP" | base64 | pastebinit -b "$URL"
	;;
	*)
		echo "ERROR"
		exit 1
	;;
esac
