.TH sandbox 1 "17 June 2011" bikeshed "bikeshed"
.SH NAME
sandbox \- create and change to a consistently named sandbox directory

.SH SYNOPSIS
\fBsandbox\fP

.SH DESCRIPTION
\fBsandbox\fP is a simple script to create a temporary directory and change to it immediately.

If TMPDIR is defined and is a directory, the temporary file will be created in $TMPDIR/sandbox.XXXXXXXX, otherwise, it will be created in /tmp/sandbox.XXXXXXXX.

With the availability of SSD hard drives, it becomes perhaps more important to use tmpfs for sandbox-ish writes.  It can be particularly useful for both your read/write performance and the health of your SSD to use tmpfs in conjuction with \fBsandbox\fP.

.SH SEE ALSO
\fBmktemp\fP(1)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.

