#!/bin/sh
#
#    wifi-status - monitor a wireless network connection
#
#    Copyright (C) 2003-2010 Dustin Kirkland <kirkland@ubuntu.com>
#
#    Authors:
#        Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -z "$1" ]; then
	dev=$(iwconfig 2>/dev/null | grep '802.11' | awk '{print $1}') 
else
	dev="$1"
fi
watch -n1 "iwconfig $dev; ifconfig $dev; (grep $dev: /var/log/syslog | tail -n 10 | sort -r)"
